mysite/api/urls.py
from django.conf.urls import url
from django.urls import include
from rest_framework import routers

from api import views

router = routers.DefaultRouter()
router.register(r'/schedule', views.ScheduleViewSet)
router.register(r'/mosque', views.MosqueViewSet)
router.register(r'/city', views.CityViewSet)
router.register(r'/province', views.ProvinceViewSet)
router.register(r'/ustad', views.UstadViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mysite/kajian/urls.py
from django.urls import path

from . import views

app_name = 'kajian'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('kajian', views.ListView.as_view(), name='list'),
    path('kajian-<int:pk>', views.DetailView.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.static import serve

admin.site.site_header = 'Jadwal Kajian'
admin.site.site_title = 'Jadwal Kajian'

urlpatterns = [
    path('', include('kajian.urls')),
    path('api', include('api.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        })
    ]

mysite/api/models.py
from django.db import models

# Create your models here.

mysite/kajian/models.py
from django.db import models

class Ustad(models.Model):
    name = models.CharField(max_length=256, null=True, blank=True)
    profile_excerpt = models.CharField(max_length=256, null=True, blank=True)
    profile = models.TextField(null=True, blank=True)
    link_youtube = models.CharField(max_length=256, null=True, blank=True)
    link_fb = models.CharField(max_length=256, null=True, blank=True)
    link_instagram = models.CharField(max_length=256, null=True, blank=True)
    link_twitter = models.CharField(max_length=256, null=True, blank=True)
    photo = models.ImageField(null=True, blank=True, upload_to='ustad')
    def __str__(self):
        return self.name

class Province(models.Model):
    name = models.CharField(max_length=256, null=True, blank=True)
    def __str__(self):
        return self.name

class City(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    name = models.CharField(max_length=256, null=True, blank=True)
    def __str__(self):
        return self.name

class Mosque(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=256, null=True, blank=True)
    photo = models.ImageField(null=True, blank=True, upload_to='mosque')
    postal_code = models.CharField(max_length=256, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    def __str__(self):
        return self.name

class Schedule(models.Model):
    ustad = models.ManyToManyField(Ustad, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    mosque = models.ForeignKey(Mosque, on_delete=models.CASCADE)
    title = models.CharField(max_length=256, null=True, blank=True)
    contact = models.CharField(max_length=256, null=True, blank=True)
    tags = models.CharField(max_length=256, null=True, blank=True)
    excerpt = models.CharField(max_length=256, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    start_from = models.DateTimeField(null=True, blank=True)
    end_to = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True, upload_to='schedule')
    def __str__(self):
        return self.title

mysite/api/views.py
# Create your views here.
from datetime import datetime

import self as self
from rest_framework import viewsets, permissions
from url_filter.integrations.drf import DjangoFilterBackend

from kajian.models import Schedule, City, Province, Mosque, Ustad
from .serializers import ScheduleSerializer, CitySerializer, ProvinceSerializer, MosqueSerializer, UstadSerializer


class ScheduleViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['title', 'ustad', 'mosque', 'city','start_from']
    serializer_class = ScheduleSerializer
    queryset = Schedule.objects.all()

    def get_queryset(self):
        type = self.request.query_params.get('type', None)
        if type is None:
            queryset = Schedule.objects.all().filter(start_from__gte=datetime.now()).order_by('-start_from')
        elif type == 'archive':
            queryset = Schedule.objects.all().order_by('start_from')
        return queryset

class MosqueViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Mosque.objects.all()
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['city']
    serializer_class = MosqueSerializer

class CityViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = City.objects.all()
    serializer_class = CitySerializer

class ProvinceViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Province.objects.all()
    serializer_class = ProvinceSerializer

class UstadViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Ustad.objects.all()
    serializer_class = UstadSerializer

mysite/kajian/views.py
from datetime import datetime
from django.views import generic
from .models import Schedule, City


class HomeView(generic.ListView):
    template_name = 'kajian/home.html'
    context_object_name = 'schedule_list'

    def get_queryset(self):
        return Schedule.objects.filter(start_from__gte=datetime.now()).order_by('start_from')[:4]

class ListView(generic.ListView):
    template_name = 'kajian/list.html'
    context_object_name = 'schedule_list'

    def get_queryset(self):
        sch = Schedule.objects
        # keyword = self.request.GET.get('keyword') or ''
        city = self.request.GET.get('city') or '0'
        if int(city) != 0:
            sch = sch.filter(city_id=city)

        sch = sch.filter(start_from__gte=datetime.now()).order_by('start_from')

        return sch

    def get_context_data(self, **kwargs):
        keyword = self.request.GET.get('keyword') or ''
        city = self.request.GET.get('city') or '0'

        context = super(ListView, self).get_context_data(**kwargs)

        context['title'] = 'Kajian Terbaru'
        context['city'] = int(city)
        context['keyword'] = keyword
        context['cities'] = City.objects.order_by('name')

        return context

class DetailView(generic.DetailView):
    model = Schedule
    template_name = 'kajian/detail.html'

mysite/kajian/templates/kajian/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Kajian Terbaru{% endblock %}</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'kajian/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'kajian/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'kajian/vendor/simple-line-icons/css/simple-line-icons.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'kajian/device-mockups/device-mockups.min.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'kajian/css/new-age.min.css' %}" rel="stylesheet">
    <link href="{% static 'kajian/css/custome.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'kajian:index' %}">Jadwal Kajian Sunnah</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Download</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'kajian:list' %}">Jadwal Terbaru</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<section class="contact bg-primary" id="contact">
    <div class="container">
        <h2>Ingin berkontribusi</h2>
        <ul class="list-inline list-social">
            <li class="list-inline-item social-twitter d-none">
                <a href="https://www.linkedin.com/in/dsasmita/" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
            </li>
            <li class="list-inline-item social-facebook  d-none">
                <a href="https://fb.com/dadang.sasmita" target="_blank">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="list-inline-item social-google-plus">
                <a href="mailto:dangs.work@gmail.com">
                    <i class="fab fa fa-envelope"></i>
                </a>
            </li>
        </ul>
    </div>
</section>

<footer>
    <div class="container">
        <p>&copy; Jadwal Kajian Sunnah Indonesia</p>
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="https://github.com/dsasmita/jadwal-kajian" target="_blank">Github</a>
            </li>
            <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/dsasmita/" target="_blank">Linkedin</a>
            </li>
        </ul>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'kajian/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'kajian/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'kajian/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5ba5b5111b076c0011d54164&product=social-ab' async='async'></script>


<!-- Custom scripts for this template -->
<script src="{% static 'kajian/js/new-age.min.js' %}"></script>

</body>

</html>

mysite/kajian/templates/kajian/detail.html
{% extends 'kajian/base.html' %}

{% block title %} {{ schedule.title }} {% endblock %}

{% block content %}
<section class="download bg-primary text-center" id="download" style="padding: 70px 0 20px 0;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h2 class="section-heading" style="font-size:25px;">{{ schedule.city.name }}</h2>
                <p>
                    {{ schedule.title }}
                </p>
            </div>
        </div>
    </div>
</section>

<section class="features" id="features" style="padding-top:35px">
    <div class="container">
        {% if schedule.photo %}
            <div class="row">
                <div class="offset-md-3 col-md-6">
                    <center>
                        <a href="{{ schedule.photo.url }}" target="_blank" title="klik download detail">
                            <img src="{{ schedule.photo.url }}" alt="{{ schedule.title }}" class="img-fluid">
                        </a>
                    </center>
                </div>
            </div>
        {% endif %}
        <hr>

        {{ schedule.description|linebreaks }}
    </div>
</section>
{% endblock %}

mysite/kajian/templates/kajian/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jadwal Kajian Sunnah</title>

    {% load static %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'kajian/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'kajian/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'kajian/vendor/simple-line-icons/css/simple-line-icons.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'kajian/device-mockups/device-mockups.min.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'kajian/css/new-age.min.css' %}" rel="stylesheet">
    <link href="{% static 'kajian/css/custome.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Jadwal Kajian Sunnah</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#download">Download</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#features">Jadwal Terbaru</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contact">Kontak</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-lg-7 my-auto">
                <div class="header-content mx-auto">
                    <h1 class="mb-5">
                        <em>Katakanlah, apakah sama antara orang yang mengetahui dengan orang yang tidak tahu</em><br>
                        <small>Az Zumar 39 : 9</small>
                    </h1>
                    <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Download</a>
                </div>
            </div>
            <div class="col-lg-5 my-auto">
                <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">
                                <!--<img src="{% static 'kajian/img/demo-screen-1.jpg' %}" class="img-fluid" alt="">-->
                            </div>
                            <div class="button">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="download bg-primary text-center" id="download">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h2 class="section-heading">Temukan kajian terbaru!</h2>
                <p>Download dan dapatkan informasi kajian terbaru langsung di smarfphone Antum!</p>
                <div class="badges">
                    <a class="badge-link" href="#"><img src="{% static 'kajian/img/google-play-badge.svg' %}"
                                                        alt=""></a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="features" id="features">
    <div class="container">
        <div class="section-heading text-center">
            <h2>Jadwal Kajian terdekat</h2>
            <p class="text-muted">
                "Jika kalian melewati taman syurga maka singgahlah dengan hati senang". <br>
                Para sahabat bertanya, "Apakah taman syurga itu?" Beliau menjawab, "halaqah-halaqah dzikir" (atau
                halaqah ilmu)
                <br>
                (HR.At-Tirmidzi)
            </p>
            <hr>
        </div>
        <div class="row">
            {% if schedule_list %}
                {% for schedule in schedule_list %}
                <div class="col-md-3">
                    <div class="card schedule-card">
                        {% if schedule.photo %}
                            <a href="{% url 'kajian:detail' schedule.id %}">
                                <img class="card-img-top" src="{{ schedule.photo.url }}" alt="{{ schedule.title }}">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text">
                                <a href="{% url 'kajian:detail' schedule.id %}">
                                    {{ schedule.title }}
                                </a><br>
                                <small>
                                    <i class="fa fa-map-marker"></i> {{ schedule.mosque.name }} - {{ schedule.city.name }}<br>
                                    <i class="fa fa-calendar-alt"></i> {{ schedule.start_from }}<br>
                                    <i class="fa fa-user"></i>
                                    {% if schedule.ustad.all %}
                                        {% for ustad in schedule.ustad.all %}
                                            {{ ustad.name }}
                                        {% endfor %}
                                    {% endif %}
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="col-md-12">
                    <center>
                        <hr>
                        <a href="{% url 'kajian:list' %}" class="btn btn-secondary btn-xl js-scroll-trigger">Selengkapnya</a>
                    </center>
                </div>
            {% else %}
            <div class="col-md-12">
                <center>-tidak ada kajian-</center>
            </div>
            {% endif %}
        </div>
    </div>
</section>

<section class="cta">
    <div class="cta-content">
        <div class="container">
            <h2>Datang Kajian<br>Perhatikan Materi<br>Amalkan Ilmunya</h2>
            <a href="#features" class="btn btn-outline btn-xl js-scroll-trigger">Kajian terdekat!</a>
        </div>
    </div>
    <div class="overlay"></div>
</section>

<section class="contact bg-primary" id="contact">
    <div class="container">
        <h2>Ingin berkontribusi</h2>
        <ul class="list-inline list-social">
            <li class="list-inline-item social-twitter  d-none">
                <a href="https://www.linkedin.com/in/dsasmita/" target="_blank">
                    <i class="fab fa-linkedin"></i>
                </a>
            </li>
            <li class="list-inline-item social-facebook  d-none">
                <a href="https://fb.com/dadang.sasmita" target="_blank">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="list-inline-item social-google-plus">
                <a href="mailto:dangs.work@gmail.com">
                    <i class="fab fa fa-envelope"></i>
                </a>
            </li>
        </ul>
    </div>
</section>

<footer>
    <div class="container">
        <p>&copy; Jadwal Kajian Sunnah Indonesia</p>
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="https://github.com/dsasmita/jadwal-kajian" target="_blank">Github</a>
            </li>
            <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/dsasmita/" target="_blank">Linkedin</a>
            </li>
        </ul>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'kajian/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'kajian/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'kajian/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'kajian/js/new-age.min.js' %}"></script>

</body>

</html>

mysite/kajian/templates/kajian/list.html
{% extends 'kajian/base.html' %}

{% block title %}Kajian Terbaru{% endblock %}

{% block content %}
<section class="download bg-primary text-center" id="download" style="padding: 70px 0 20px 0;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h2 class="section-heading" style="font-size: 25px">Jadwal Kajian terdekat</h2>
            </div>
        </div>
    </div>
</section>

<section class="features" id="features" style="padding-top:35px">
    <div class="container">
        <form action="#" method="get">
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" name="keyword" value="{{ keyword }}" placeholder="kata kunci">
                </div>
                <div class="col">
                    <select class="custom-select" name="city">
                        <option value="">-pilih kota-</option>
                        {% if cities %}
                            {% for ct in cities %}
                                <option {% if ct.id == city %} selected {% endif %}value="{{ ct.id }}">{{ ct.name }}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-info">Cari Kajian</button>
                </div>
            </div>
        </form>
        <hr>
        <div class="row">
            {% if schedule_list %}
                {% for schedule in schedule_list %}
                <div class="col-md-3">
                    <div class="card schedule-card">
                        {% if schedule.photo %}
                            <a href="{% url 'kajian:detail' schedule.id %}">
                                <img class="card-img-top" src="{{ schedule.photo.url }}" alt="{{ schedule.title }}">
                            </a>
                        {% else %}
                            <a href="{% url 'kajian:detail' schedule.id %}">
                                <img class="card-img-top" src="https://via.placeholder.com/350x350?text=jadwal" alt="{{ schedule.title }}">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <p class="card-text">
                                <a href="{% url 'kajian:detail' schedule.id %}">
                                    {{ schedule.title }}
                                </a><br>
                                <small>
                                    <i class="fa fa-map-marker"></i> {{ schedule.mosque.name }} - {{ schedule.city.name }}<br>
                                    <i class="fa fa-calendar-alt"></i> {{ schedule.start_from }}<br>
                                    <i class="fa fa-user"></i>
                                    {% if schedule.ustad.all %}
                                        {% for ustad in schedule.ustad.all %}
                                            {{ ustad.name }}
                                        {% endfor %}
                                    {% endif %}
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
            <div class="col-md-12">
                <center>-tidak ada kajian-</center>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}